### ISSUE TITLE
Remove session if the file has already been transmitted

### ISSUE THREAD

**Issue by xaldarof** [niyozbekmirzayev/Tuynuk#1]
https://github.com/niyozbekmirzayev/Tuynuk/blob/04fb6919eb5718d7b20453d37c9b1c5a4c3cc9d8/Tuynuk/Hubs/Sessions/SessionHub.cs#L7

**Comment by niyozbekmirzayev** [comment]
#4 Session + Client + File are removed when the receiver client downloads the file
