### ISSUE TITLE
Implement automatic session deletion upon creation

### ISSUE THREAD

**Issue by xaldarof** [niyozbekmirzayev/Tuynuk#2]
https://github.com/niyozbekmirzayev/Tuynuk/blob/04fb6919eb5718d7b20453d37c9b1c5a4c3cc9d8/Tuynuk/Hubs/Sessions/SessionHub.cs#L7

**Comment by niyozbekmirzayev** [comment]
#7 Hangfire background service added to remove abandoned sessions
